### ISSUE TITLE
Specify LICENSE to distribute this under

### ISSUE THREAD

**Issue by luzpaz** [altangarts/FreeCAD-Themes-ColorPalette#4]
Some people use GPLv3, some use LGPLv2.1  
Please choose.

**Comment by luzpaz** [comment]
https://github.com/Altan-g/FreeCADColorPaletteTheme/blob/main/LICENSE

Note: GPLv3 will not allow FreeCAD to distribute these themes. So they will need to be addons

**Comment by altangarts** [comment]
I can add whatever license version is required for distribution.
